### ISSUE TITLE
sentinel-dashboard可以提供源码？

### ISSUE THREAD

**Issue by Kevin-Ben** [songxc9527/sentinel-demo#1]
谢谢。

**Comment by songxc9527** [comment]
已提供。
https://github.com/songxc9527/sentinel-demo/tree/master/sentinel-dashboard

**Comment by SeekYao** [comment]
你这个[sentinel-dashboard]代码不对吧？？？   完全跟官方一样的，都没动过， Cluster相关的改动没看到

**Comment by songxc9527** [comment]
> 你这个[sentinel-dashboard]代码不对吧？？？ 完全跟官方一样的，都没动过， Cluster相关的改动没看到

sentinel-dashboard/src/main/webapp/resources/app/scripts/directives/sidebar/sidebar.html 中 流控规则 V1 是v2版本
